### PR TITLE
Define and use ForwardDiffRuleConfig

### PR DESCRIPTION
**Pull request by mohdibntarek**
This PR was needed to get ImplicitDifferentiation to use ForwardDiffChainRules. With this PR, this works.
```julia
using ImplicitDifferentiation
using Optim
using Random
using ForwardDiff, ForwardDiffChainRules

Random.seed!(63)
function dumb_identity(x)
    f(y) = sum(abs2, y-x)
    y0 = zero(x)
    res = optimize(f, y0, LBFGS(); autodiff=:forward)
    y = Optim.minimizer(res)
    return y
end;
zero_gradient(x, y) = 2(y - x);
implicit = ImplicitFunction(dumb_identity, zero_gradient);
x = rand(3, 2)
@ForwardDiff_frule (f::typeof(implicit))(x::AbstractMatrix{<:ForwardDiff.Dual})
ForwardDiff.jacobian(implicit, x)
```

### CODE REVIEW

**Comment by mohdibntarek** [comment]
I need to add the ImplicitDiff example as a test case.

**Comment by mohdibntarek** [comment]
ImplicitDifferentiation is not compatible with Julia 1.6 so I am dropping it from CI. Any objection?

**Comment by ThummeTo** [comment]
> ImplicitDifferentiation is not compatible with Julia 1.6 so I am dropping it from CI. Any objection?

basically Julia 1.6 is still the LTS-version... on the other hand not many libraries are focusing on keeping a support for the LTS... this is a bit ambivalent... but it would be ok for me.

BTW: Should we transfer the Repo to your user? You are far more involved in code changes etc.

**Review by ThummeTo — APPROVED** [review]

**Comment by mohdibntarek** [comment]
>BTW: Should we transfer the Repo to your user? You are far more involved in code changes etc.

I don't mind, up to you. Also ok with keeping it yours.

**Comment by gdalle** [comment]
> ImplicitDifferentiation is not compatible with Julia 1.6 so I am dropping it from CI. Any objection?

Refreshing the repo right now and I don't think there's any obstacle to 1.6 compatibility, guess we'll find out

**Comment by gdalle** [comment]
> ```julia
> ForwardDiff.jacobian(implicit, x)
> ```
Actually this example is not necessarily a good choice, because
```julia
ForwardDiff.jacobian(dumb_identity, x)
```
works as well. Gonna try to come up with something better

**Pull request merged**
